parameters:
#    encyclopedia_front.example.class: Encyclopedia\FrontBundle\Example

services:
#    encyclopedia_front.example:
#        class: %encyclopedia_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
