encyclopedia_admin_homepage:
    path:  /{_locale}/
    defaults: { _controller: EncyclopediaAdminBundle:Default:index, _local: en }
simple_admin_homepage:
    path:  /
    defaults: { _controller: EncyclopediaAdminBundle:Default:index }
_admin_login:
    path: /{_locale}/login
    defaults: { _controller: EncyclopediaAdminBundle:Security:login }
_admin_login_check:
    path: /{_locale}/login_check
_admin_logout:
    path: /{_locale}/logout
# importe les routes d'un répertoire Controller
admin:
    resource: "@EncyclopediaAdminBundle/Controller"
    type:     annotation
