encyclopedia_admin_homepage:
    pattern:  /
    defaults: { _controller: EncyclopediaAdminBundle:Default:index }
_admin_login:
    pattern: /login
    defaults: { _controller: EncyclopediaAdminBundle:Security:login }
_admin_login_check:
    pattern: /login_check
_admin_logout:
    pattern: /logout
# importe les routes d'un répertoire Controller
admin:
    resource: "@EncyclopediaAdminBundle/Controller"
    type:     annotation
