parameters:
#    encyclopedia_admin.example.class: Encyclopedia\AdminBundle\Example

services:
#    encyclopedia_admin.example:
#        class: %encyclopedia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
