_publishing:
    pattern:  /
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:index" }

_publishing_show:
    pattern:  /{id}/show
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:show" }

_publishing_new:
    pattern:  /new
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:new" }

_publishing_create:
    pattern:  /create
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:create" }
    requirements: { _method: post }

_publishing_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:edit" }

_publishing_update:
    pattern:  /{id}/update
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:update" }
    requirements: { _method: post|put }

_publishing_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EncyclopediaAdminBundle:Publishing:delete" }
    requirements: { _method: post|delete }
