parameters:
    languages: "(en|fr)"
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: polaris1890, roles: 'ROLE_SUPER_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|less)/
            security: false

        admin_secured_area:
            provider: in_memory
            pattern:    ^/admin
            anonymous: ~
            form_login:
                login_path:  _admin_login
                check_path:  _admin_login_check
            logout:
                path: _admin_logout
                target: _admin_login
                invalidate_session: false
            http_basic:
                realm: "Secured Admin Area"      
        
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/%languages%/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/%languages%/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        
        
