parameters:
#    encyclopedia_library.example.class: Encyclopedia\LibraryBundle\Example

services:
#    encyclopedia_library.example:
#        class: %encyclopedia_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
